---
  - name: Disable Swap
    shell: swapoff -a
    when: cat /proc/swaps | grep -c file > 0

  - name: Cleanup fstab
    replace:
      path: /etc/fstab
      regexp: "(^[^#].*swap*)"
      replace: '#\1'