---
  - name: Ensure old versions of Docker are not installed.
    yum:
      name:
        - docker
        - docker-common
        - docker-engine
      state: absent
  - name: Install kubernetes related packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - kubeadm
      - kubelet
      - kubectl