---
- name: Install kubernetes related packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Starting and Enabling the required services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"
